[project]
name = "first"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pillow>=11.3.0",
    "uvicorn>=0.35.0",
]

[tool.uv.workspace]
members = [
    "second",
]
